deliverest/urls.py
# -*- coding: utf-8 -*-

"""Deliverest URL definitions."""

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from delicontent.views import page
from delicontacts.views import account_settings, delete_account
from deliorders.views import home, search, add_to_cart, load_order, add_dialog, cart, confirm_cart, cart_status, user_confirmed_tf
from deliproducts.views import price, search_ajax

from deliproducts.sitemaps import sitemaps


urlpatterns = [
    url(r'^$', home,
        name="home"),
    url(r'^categoria/(?P<category>[^/]+)/$',
        home, name="category"),
    url(r'^buscar/$',
        search, name="search"),
    url(r'^agregar/$',
        add_to_cart, name="add_to_cart"),
    url(r'^agregar-producto/$',
        add_dialog, name="add_dialog"),
    url(r'^producto/(?P<id>[^/]+)$',
        price, name="price_redir"),
    url(r'^productos/(?P<slug_id>[^/]+)$',
        price, name="price"),
    url(r'^pagina/(?P<slug>[^/]+)$',
        page, name="page"),
    url(r'^recargar-pedido/$',
        load_order, name="load_order"),
    url(r'^canasta/$',
        cart, name="shopping_cart"),
    url(r'^confirmar-canasta/$',
        confirm_cart, name="confirm_cart"),
    url(r'^estado-canasta/$',
        cart_status, name="cart_status"),
    url(r'^confirm-tf/$',
        user_confirmed_tf, name="confirm_tf"),

    url(r'^buscar-ajax/$',
        search_ajax, name="product_search_ajax"),

    url(r'^cuenta/$',
        account_settings, name="account_settings"),
    url(r'^cuenta/(?P<mode>[^/]+)/$',
        account_settings, name="account_settings_mode"),
    url(r'^borrarcuenta/$',
        delete_account, name="account_delete"),

    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Robots.txt
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),


    # Auth views
    url('^', include('django.contrib.auth.urls')),

    # Social login related
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

deliproducts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.utils.functional import cached_property
from django.core.urlresolvers import reverse

from markdownx.models import MarkdownxField

UNIT_L = 'L'
UNIT_ML = 'CC'
UNIT_G = 'G'
UNIT_KG = 'KG'
UNIT_UNIT = 'U'

UNIT_CHOICES = (
    (UNIT_L, _(u'litro')),
    (UNIT_ML, _(u'cc')),
    (UNIT_G, _(u'gramo')),
    (UNIT_KG, _(u'kilogramo')),
    (UNIT_UNIT, _(u'unidad'))
)

UNIT_CHOICES_PLURAL = {
    UNIT_L: _(u'litros'),
    UNIT_G: _(u'gramos'),
    UNIT_KG: _(u'kilogramos'),
    UNIT_UNIT: _(u'unidades')
}


class ActiveManager(models.Manager):
    use_for_related_fields = True

    def active(self):
        return super(ActiveManager, self).all().filter(is_active=True)


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(
        verbose_name=_(u'nombre'),
        max_length=150,
        unique=True)
    slug = models.SlugField(
        max_length=50,
        verbose_name=_(u'direccion web'),
        unique=True,
        null=True)
    order = models.PositiveIntegerField(verbose_name=_('orden'), null=True)
    is_active = models.BooleanField(verbose_name=_('activo'), default=True)
    parent = models.ForeignKey(
        'self',
        verbose_name=(u'categoría padre'),
        related_name='subcategories',
        null=True,
        blank=True)

    color = models.CharField(
        verbose_name=_(u'color'),
        help_text=_(u'color de identificación de la categoría'),
        max_length=8,
        null=True,
        blank=True)
    children_color = models.CharField(
        verbose_name=_(u'color de los hijos'),
        help_text=_(u'color de identificación para los '
                    u'hijos de esta categoría'),
        max_length=8,
        null=True,
        blank=True)

    objects = ActiveManager()

    class Meta:
        verbose_name = _(u'categoría')
        verbose_name_plural = _(u'categorías')
        ordering = ('order',)

    def parent_crumbs(self, instance=None, crumb_str=None):
        if instance is None:
            instance = self
            crumb_str = self.name

        if instance.parent is not None:
            crumb_str = u"%s > %s" % (instance.parent.name, crumb_str)
            return self.parent_crumbs(instance.parent, crumb_str)

        else:
            return crumb_str

    def get_absolute_url(self):
        return reverse(
            'deliorders.views.home',
            kwargs={'category': self.slug})

    def __str__(self):
        return self.parent_crumbs()


@python_2_unicode_compatible
class Presentation(models.Model):

    name = models.CharField(
        max_length=150,
        verbose_name=_(u'nombre'))
    plural_name = models.CharField(
        max_length=150,
        verbose_name=_(u'plural'))
    quantifiable = models.BooleanField(
        default=True,
        verbose_name=_(u'cuantificable'))
    quantity = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name=_(u'cantidad'),
        blank=True,
        null=True)
    measure_unit = models.CharField(
        max_length=2,
        choices=UNIT_CHOICES,
        blank=True,
        null=True)

    class Meta:
        verbose_name = _(u'presentación')
        verbose_name_plural = _(u'presentaciones')
        unique_together = ('name', 'quantity', 'measure_unit')
        ordering = ('name', 'quantity', 'measure_unit')

    def __str__(self):
        if self.quantity is not None:
            return u"%s de %s %s" % (
                self.name,
                self.quantity if self.quantity.to_integral() - self.quantity else self.quantity.to_integral(),
                self.get_measure_unit_display() if (self.quantity == 1) or (self.measure_unit not in UNIT_CHOICES_PLURAL) else UNIT_CHOICES_PLURAL[self.measure_unit])
        else:
            return self.name

    @cached_property
    def plural_repr(self):
        if self.quantity is not None:
            return u"%s de %s %s" % (
                self.plural_name,
                self.quantity if self.quantity.to_integral() - self.quantity else self.quantity.to_integral(),
                self.get_measure_unit_display() if (self.quantity == 1) or (self.measure_unit not in UNIT_CHOICES_PLURAL) else UNIT_CHOICES_PLURAL[self.measure_unit])
        else:
            return self.plural_name

    def unit_display(self):
        if self.quantity is not None:
            return "%0.f %s" % (
                self.quantity,
                self.get_measure_unit_display() if (self.quantity == 1) or (self.measure_unit not in UNIT_CHOICES_PLURAL) else UNIT_CHOICES_PLURAL[self.measure_unit])
        else:
            return self.name


@python_2_unicode_compatible
class Product(models.Model):

    name = models.CharField(
        max_length=200,
        verbose_name=_(u'nombre'),
        unique=True
    )
    description = models.TextField(verbose_name=_(u'descripción'), help_text=_(u'descripción que se muestra en los listados de producto'), blank=True)
    long_description = MarkdownxField(verbose_name=_(u'descripción larga'), help_text=_(u'descripción que se muestra en el detalle de producto'), blank=True)
    presentations = models.ManyToManyField(Presentation, through='Price')
    provider = models.ForeignKey('Provider', verbose_name=_(u'proveedor'), blank=True, null=True)

    category = models.ForeignKey(
        'Category',
        verbose_name=_(u'categoría'),
        null=True,
        blank=True)
    is_active = models.BooleanField(verbose_name=_(u'activo'), default=True)

    objects = ActiveManager()

    class Meta:
        verbose_name = _(u'producto')
        verbose_name_plural = _(u'productos')
        ordering = ('name',)

    def __str__(self):
        return u"%s" % (self.name)

CURRENCY_CHOICE = (
    ('ARS', _(u'Peso argentino')),
    ('USD', _(u'Dolar'))
)


@python_2_unicode_compatible
class Price(models.Model):
    product = models.ForeignKey(Product, verbose_name=_(u'producto'))
    presentation = models.ForeignKey(
        Presentation,
        verbose_name=_(u'presentación'))
    in_stock = models.BooleanField(
        verbose_name=_(u'en stock'),
        default=True)
    wholesale = models.BooleanField(
        verbose_name=_(u'Por mayor'),
        default=False)
    currency = models.CharField(
        max_length=3,
        choices=CURRENCY_CHOICE,
        default='ARS',
        verbose_name=_(u'moneda'))
    sell_price = models.DecimalField(
        max_digits=20,
        decimal_places=4,
        verbose_name=_(u'precio de venta'))
    buy_price = models.DecimalField(
        max_digits=20,
        decimal_places=4,
        verbose_name=_(u'precio de compra'))
    featured = models.BooleanField(default=False, verbose_name=_(u'destacado'))
    is_active = models.BooleanField(verbose_name=_(u'activo'), default=True)

    objects = ActiveManager()

    class Meta:
        verbose_name = _(u'precio')
        verbose_name_plural = _(u'precios')
        unique_together = ('product', 'presentation', 'wholesale')
        ordering = ('product__name', )

    def __str__(self):
        return u"%s (%s): $%.2f" % (
            self.product.name,
            self.presentation,
            self.sell_price)

    @property
    def slug_id(self):
        from django.utils.text import slugify
        return "{}-{}".format(self.id, slugify(self.product.name))

    def get_absolute_url(self):
        return reverse(
            'price',
            kwargs={'slug_id': self.slug_id}
        )


@python_2_unicode_compatible
class Provider(models.Model):
    code = models.CharField(max_length=50, verbose_name=_(u'código'))
    name = models.CharField(max_length=150, verbose_name=_(u'nombre'))
    address = models.TextField(verbose_name=_(u'dirección'), blank=True)
    phone = models.CharField(
        max_length=100,
        verbose_name=_(u'teléfono'),
        blank=True)

    class Meta:
        verbose_name = _(u'proveedor')
        verbose_name_plural = _(u'proveedores')
        ordering = ('name',)

    def __str__(self):
        return u"%s (%s)" % (self.name, self.code)

deliorders/templates/add_dialog.html
<h4>{{ product.name }}</h4>
<p>{{ product.description }}</p>
<dl class="dl-horizontal">
  <dt>Presentación</dt>
  <dd>{{ selected_price.presentation }}</dd>
  <dt>Precio</dt>
  <dd>$&nbsp;{{ selected_price.sell_price|floatformat:2 }}</dd>
</dl>
{% if existing_items %}
<h4>Este producto ya está en tu canasta</h4>
<ul>
    {% for item in existing_items %}<li><strong>{{ item.quantity }}</strong> {% if item.quantity == 1 %}{{ item.product.presentation|lower }}{% else %}{{ item.product.presentation.plural_repr|lower }}{% endif %}</li>{% endfor %}
</ul>
{% endif %}
<form action="#" method="post">
<div class="form-group">
    <label for="quantity">Cantidad</label>
    <input name="quantity" value="1" class="form-control input" />
</div>
{% if product.price_set.active|length > 1 %}
<div class="form-group">
    <label for="price_id">¿Preferís alguna de estas alternativas?</label>
    {% for price in product.price_set.active %}
    <div class="radio" {% if price.id == selected_price.id %}style="display: none;"{% endif %}>
      <label class="radio-inline"><input type="radio" name="price_id" value="{{ price.id }}" id="price_id_{{ price.id }}" data-price-name="{{ price.product.name }} ({{ price.presentation }})" {% if price.id == selected_price.id %}checked{% endif %}>{{ price }}</label>
    </div>
    {% endfor %}
</div>
{% else%}
<input type="hidden" name="price_id" value="{{ selected_price.id }}" data-price-name="{{ selected_price.product.name }} ({{ selected_price.presentation }})" />
{% endif %}
<div class="form-group">
    <label for="comments">¿Nos querés dejar un comentario?</label>
    <input name="comments" class="form-control input" />
</div>
<div class="modal-footer">
  {% if is_logged_in %}
  <button type="button" class="btn btn-info" onclick="btnAddToCart(event)" data-dismiss="modal">Agregar</button>
  {% else %}
  <p style="text-align:center">Necesitas iniciar sesión para agregar productos a la canasta.</p>
  <a class="btn btn-primary form-control" data-dismiss="modal" data-toggle="modal" data-target="#login-modal">Inicia sesión</a>
  {% endif %}
</div>
</form>

deliorders/templates/cart.html
{% extends "organicos_base.html" %}
{% load i18n %}
{% block content %}

<div class="container container-bar">
    <div class="row">
        {% if empty_cart %}
        <h2>Tu canasta está vacía.</h2>
        {% else %}
        <h2>El detalle de tu pedido ({{ order.code }})</h2>

        {% if tf_closed and order.status == 10 %}
        <p class="lead"><strong>Nota importante: </strong>los pedidos para la próxima entrega ya están cerrados. Si confirmás ahora, tu pedido se entregará entre el {{ tf_delivery_start|date:"d \d\e F"|lower }} y el {{ tf_delivery_end|date:"d \d\e F"|lower }} dependiendo de la forma de envío elegida.</p>
        {% endif %}

        {% if order.status == 10 %}
        <form method="post">
            {% csrf_token %}
            {% else %}
            <p class="lead">Tu pedido está confirmado</p>
            {% endif %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <th width="3%"></th>
                        <th width="10%">Cantidad</th>
                        <th>Producto</th>
                        <th>Presentación</th>
                        <th width="10%" class="cart-price">Unitario</th>
                        <th width="10%" class="cart-price">Total</th>
                        <th>Pedidos especiales</th>
                    </thead>
                    <tbody>
                        {% for item in order.orderitem_set.all %}
                        <tr>
                            <td id="{{ item.id }}">{% if order.status == 10 %}<a href="#" onclick="removeItem(event)"><span class="glyphicon glyphicon-trash"></span></a>{% endif %}</td>
                            <td>{% if order.status == 10 %}<input type="number" onchange="checkQtyValue(this)" class="form-control input-sm quantity" name="quantity_{{ item.id }}" value="{{ item.quantity }}" />{% else %}{{ item.quantity }}{% endif %}</td>
                            <td>{{ item.product.product }}</td>
                            <td>{{ item.product.presentation }}</td>
                            <td align="right" class="cart-price">$&nbsp;{{ item.sell_price|floatformat:2 }}</td>
                            <td align="right" class="cart-price">$&nbsp;{{ item.item_total|floatformat:2 }}</td>
                            <td>
                                {% if order.status == 10 %}
                                <a href="#" {% if item.comments %}style="display:none;"{% endif %} onclick="toggleInput(this)"><span class="glyphicon glyphicon-comment"></span></a>
                                <input type="text" {% if not item.comments %}style="display:none;"{% endif %} class="form-control input-sm comment" onchange="checkQtyValue(this)" class="form-control input-sm" name="comment_{{ item.id }}" value="{{ item.comments }}" onblur="blurComments(this)" />
                                {% else %}{{ item.comments }}{% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        {% if order.status >= 20 and order.delivery_price %}
                        <tr>
                            <td id="delivery_price"></td>
                            <td>1</td>
                            <td>{{ order.delivery_method }}</td>
                            <td></td>
                            <td align="right" class="cart-price">$&nbsp;{{ order.delivery_price|floatformat:2 }}</td>
                            <td align="right" class="cart-price">$&nbsp;{{ order.delivery_price|floatformat:2 }}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td colspan="4" align="right" class="cart-price"><strong>Total</strong></td>
                            <td align="right" class="cart-price"><strong>$&nbsp;{{ order.get_order_total|floatformat:2 }}</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        {% else %}
                        <tr>
                            <td>&nbsp;</td>
                            <td colspan="4" align="right" class="cart-price"><strong>Total (sin envío)</strong></td>
                            <td align="right" class="cart-price"><strong>$&nbsp;{{ order.get_order_total_without_delivery|floatformat:2 }}</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            {% if order.status == 10 %}
            <button type="submit" id="update-button" disabled class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Modificar pedido</button>
            &nbsp;
            <a href="{% url 'home' %}" id="back-button" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span>&nbsp;Continuar comprando</a>
        </form>
        {% endif %}
    </div>
    {% if order.status == 10 %}
    <form method="post" action="{% url 'confirm_cart' %}">
        <div class="row">
            {% csrf_token %}
            <div class="col-md-8">
                <h2>Detalles de la entrega</h2>
                <div class="form-group">
                    <label for="delivery_method">Método de entrega</label>
                    <select class="form-control" id="delivery_method" name="delivery_method">
                        <option value="" {% if order.delivery_method_id == None %}selected{% endif %}>--------</option>
                        {% for dm in delivery_methods %}
                        <option value="{{dm.id}}" {% if order.delivery_method_id == dm.id %}selected{% endif %}>{{ dm.name }} {% if dm.delivery_price %}($&nbsp;{{ dm.delivery_price|floatformat:2 }}){% else %}({% trans 'sin costo' %}){% endif %}</option>
                        {% endfor %}
                    </select>
                    <span class="error text-danger">{{ errors.delivery_method }}</span>
                </div>
                <div class="form-group">
                    <label for="address">Dirección de envío</label>
                    <textarea class="form-control" id="delivery_address" name="delivery_address">{{ customer.address }}</textarea>
                </div>
                <div class="form-group">
                    <label for="comments">Comentarios y pedidos especiales</label>
                    <textarea class="form-control" id="user_comments" name="user_comments">{{ order.user_comments }}</textarea>
                </div>
            </div>
        </div>
        <div class="row">
            <button type="submit" class="btn btn-primary cart-price"><span class="glyphicon glyphicon-ok"></span>&nbsp;Finalizar la compra</button>
        </div>
    </form>
    {% else %}
    <dl class="dl-horizontal">
        <dt>Forma de entrega</dt>
        <dd>{{ order.delivery_method }}</dd>
        {% if order.delivery_method.is_delivery %}
        <dt>Dirección de envío</dt>
        <dd>{{ order.delivery_address }}</dd>
        {% endif %}
        <dt>Fecha de entrega</dt>
        <dd>{{ order.delivery_date|date:"l d \d\e F \d\e Y"|lower|capfirst }}</dd>
        <dt>Hora de entrega</dt>
        <dd>{{ order.delivery_method.delivery_time|capfirst }}</dd>
    </dl>
    <p><small>Tu pedido está siendo procesado. Proximamente recibirás nuestra confirmación.</small></p>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
{% if order.status == 10 %}
<script type="text/javascript">
    function removeItem(ev) {
        ev.preventDefault();
        var $inpt = $(ev.target).closest('tr').find('.quantity');
        $inpt.val(0);
        checkQtyValue($inpt);
    }
    function checkQtyValue(inpt) {
        $('.cart-price').fadeOut(800);
        $('#update-button').attr('disabled', false);
        elAlert = $('<div class="alert alert-warning alert-dismissible alert-fixed" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>Modificaste el pedido. Hacé click en <strong>Modificar pedido</strong> para actualizar los precios.</div>');
        var aWrapper = $('#alert-wrapper');
        aWrapper.children().alert('close');
        aWrapper.append(elAlert);
        elAlert.fadeIn(800);
        setTimeout(function closeAlert(){
            elAlert.alert('close');
        }, 5000);

        if ($(inpt).hasClass('quantity')) {
            if (parseFloat($(inpt).val()) > 0) {
                $(inpt).closest('tr').removeClass('removed');
            }
            else {
                $(inpt).closest('tr').addClass('removed');
            }
        }
    }

    function toggleInput(btn) {
        $(btn).toggle();
        var input = $(btn).next();
        input.fadeToggle();
        input.focus();
        return false;
    }

    function blurComments(input) {
        input = $(input);
        if (input.val())
            return;
        input.prev().fadeToggle();
        input.toggle();
    }
</script>
{% endif %}
{% endblock %}

deliorders/templates/cart_status.html
{% if order.orderitem_set.all %}
<h4><a href="{% url 'shopping_cart' %}"><img class="shopping-basket" src="/static/images/basket_pink.svg"></img>&nbsp;Tu lista&nbsp;-&nbsp;Finalizar pedido</a></h4>
{% endif %}
<ul class="list-group cart-list" id="cart-status">
    {% for item in order.orderitem_set.all %}
    <form method="post">
    <li class="list-group-item row">
    <div class="col-xs-10">
    <input type="hidden" name="price_id" value="{{ item.product.id }}" />
    <a href="{% url 'shopping_cart' %}#{{ item.id }}">{{ item.quantity }} {%if item.quantity == 1%}{{ item.product.presentation.name|lower }}{% else %}{{ item.product.presentation.plural_name|lower }}{% endif %} de <strong>{{ item.product.product.name|lower }}</strong> ($&nbsp;{{ item.item_total|floatformat:2 }})</a>
    </div>
    <div class="text-right col-xs-2 pull-right">
    <a href="#" onclick="btnAddToCart(event, 1)"><span class="glyphicon glyphicon-plus-sign"></span></a>
    <a href="#" onclick="btnAddToCart(event, -1)"><span class="glyphicon glyphicon-minus-sign"></span></a>
    </div>
    </li>
    </form>
    {% endfor %}
    {% if order.orderitem_set.count %}
    <li class="list-group-item row">
    <div class="col-xs-10 text-muted">
    Total hasta ahora: <strong>$&nbsp;{{ order.get_order_total_without_delivery|floatformat:2 }}</strong>
    </div>
    </li>
    {% endif %}
</ul>

deliorders/templates/home.html
{% extends "organicos_base.html" %}
{% load bootstrap3 %}

    {% block title %}{% if category_browse %}{{selected_category.name}} - {% endif %}Organicos de mi tierra - mercado de alimentos saludables en Córdoba{% endblock %}
    {% block content %}
    <div id="wrapper">
    {% if not category_browse %}
    <div class="jumbotron" style="padding:31px 0 0 0;">
        <div class="carousel-holder">
            <div id="promo-carousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for promo_image in promo_images %}
                    <li data-target="#promo-carousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.counter0 == 0 %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for promo_image in promo_images %}
                    <div class="item{% if forloop.counter0 == 0 %} active{% endif %}">
                        <img class="slide-image" src="{{ promo_image.image.url }}" alt="{{ promo_image.description }}">
                    </div>
                    {% endfor %}
                </div>
                <a class="left carousel-control" href="#promo-carousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#promo-carousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>

        </div>
    </div>
    {% endif %}
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" id="products-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Nuestros productos
                    </a>
                </li>
                <li>
                    {% for category in categories %}
                    <a href="{% url 'category' category=category.slug %}"class="{% if category.subcategories.active.exists %}has-children{% endif %} {% if selected_category == category %}selected-category{% endif %}">{{ category.name }}</a>
                        {% if selected_category == category or selected_category.parent == category %}
                        {% for subcategory in category.subcategories.active %}
                        <a href="{% url 'category' category=subcategory.slug %}" class="inner {% if selected_category == subcategory %}selected-category{% endif %}">{{ subcategory.name }}</a>
                        {% endfor %}
                        {% endif %}
                    {% endfor %}
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <div id="page-content-wrapper" {% block containerprops %}{% endblock %}>
            <div class="container-fluid {% if category_browse %}container-bar{% endif %}">
                {% if category_browse %}<h1>{% block containertitle %}{{ selected_category.parent_crumbs }}{{ category_header }} <em>{{ category_header_additional }}</em>{% endblock %}</h1>{% endif %}
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-9">
                    {% block maincontent %}
                        {% for price in products %}
                        {% if forloop.first %}
                        <div class="row">
                            {% endif %}
                            <div class="col-sm-4">
                                <div class="thumbnail">
                                    <div class="caption-full">
                                        <h4><a href="{% url 'price' price.slug_id %}" {% if not config.ORDERS_SUSPENDED %}onclick="btnAddProductDialog({{ price.id }}, event)"{% endif %}>{{ price.product.name }}</a></h4>
                                        <p>{{ price.presentation }}</p>
                                        {% if price.product.description %}<p>{{ price.product.description }}</p>{% endif %}
                                        <p>$&nbsp;{{ price.sell_price|floatformat:2 }}</p>
                                        <div class="form-group">
                                            <button {% if not config.ORDERS_SUSPENDED %}onclick="btnAddProductDialog({{ price.id }}, event)" class="btn btn-info"{% else %}onclick="$('#suspend-modal').modal()" class="btn btn-disabled" disabled{% endif %}><span class="glyphicon glyphicon-plus"></span>&nbsp;Agregar</button>
                                            {% if request.user.is_staff %}
                                            <a class="btn btn-primary" href="{% url 'admin:deliproducts_price_change' price.id %}"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Editar</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% if forloop.counter|divisibleby:3 and not forloop.last %}
                        </div>
                        <div class="row">
                        {% elif forloop.last %}
                        </div>
                        {% endif %}
                        {% endfor %}
                    {% endblock %}
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-3">
                        <div id="cart-status">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
    <!-- /#wrapper -->
    {% endblock %}

    {% block dialogs %}
    {% endblock %}

    {% block javascript %}
    {% if not config.ORDERS_SUSPENDED %}
    <script type="text/javascript">
        $(function(){
            updateCartStatus();
        });

    function updateCartStatus(promise) {
        var $cartStatus = $('#cart-status');
        if (!$cartStatus.is(':visible'))
            $cartStatus = $('#cart-status-sm');
        $cartStatus.fadeOut(100);
        
        $.when(promise)
        .then(function(){
            $.ajax({
                url: '{% url "cart_status" %}',
            })
            .then(function(data) {
                $cartStatus.html(data);
                $cartStatus.fadeIn(200);
            });            
        });
    }
    </script>
    {% endif %}
    {% endblock %}