deliverest/urls.py
# -*- coding: utf-8 -*-

"""Deliverest URL definitions."""

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from delicontent.views import page
from delicontacts.views import account_settings, delete_account
from deliorders.views import home, search, add_to_cart, load_order, add_dialog, cart, confirm_cart, cart_status, user_confirmed_tf
from deliproducts.views import price, search_ajax

from deliproducts.sitemaps import sitemaps


urlpatterns = [
    url(r'^$', home,
        name="home"),
    url(r'^categoria/(?P<category>[^/]+)/$',
        home, name="category"),
    url(r'^buscar/$',
        search, name="search"),
    url(r'^agregar/$',
        add_to_cart, name="add_to_cart"),
    url(r'^agregar-producto/$',
        add_dialog, name="add_dialog"),
    url(r'^producto/(?P<id>[^/]+)$',
        price, name="price_redir"),
    url(r'^productos/(?P<slug_id>[^/]+)$',
        price, name="price"),
    url(r'^pagina/(?P<slug>[^/]+)$',
        page, name="page"),
    url(r'^recargar-pedido/$',
        load_order, name="load_order"),
    url(r'^canasta/$',
        cart, name="shopping_cart"),
    url(r'^confirmar-canasta/$',
        confirm_cart, name="confirm_cart"),
    url(r'^estado-canasta/$',
        cart_status, name="cart_status"),
    url(r'^confirm-tf/$',
        user_confirmed_tf, name="confirm_tf"),

    url(r'^buscar-ajax/$',
        search_ajax, name="product_search_ajax"),

    url(r'^cuenta/$',
        account_settings, name="account_settings"),
    url(r'^cuenta/(?P<mode>[^/]+)/$',
        account_settings, name="account_settings_mode"),
    url(r'^borrarcuenta/$',
        delete_account, name="account_delete"),

    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

    # Robots.txt
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),


    # Auth views
    url('^', include('django.contrib.auth.urls')),

    # Social login related
    url(r'^accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

delicontacts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from delidelivery.models import DeliveryMethod

CONTACT_MODE_CHOICES = (
    (50, _(u'Web')),
    (100, _(u'E-mail')),
    (200, _(u'Facebook')),
    (300, _(u'Telefono')),
    (400, _(u'Otro')),
)


@python_2_unicode_compatible
class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name=_(u'nombre'))
    email = models.EmailField(verbose_name=_(u'e-mail'))
    address = models.TextField(verbose_name=_(u'dirección de envío'))
    phone = models.CharField(max_length=200, verbose_name=_(u'teléfono'))

    class Meta:
        verbose_name = _(u'persona')
        verbose_name_plural = _(u'personas')
        ordering = ('name',)

    def __str__(self):
        return u"%s" % (self.name)


@python_2_unicode_compatible
class Customer(Person):
    contact_mode = models.IntegerField(choices=CONTACT_MODE_CHOICES, default=100, verbose_name=_(u'forma de contacto'))
    prefered_delivery_method = models.ForeignKey(
        DeliveryMethod,
        verbose_name=_(u'forma de envío preferida'),
        on_delete=models.PROTECT,
    )
    last_confirmed_tf = models.DateTimeField(
        verbose_name=_(u'última confirmación de ventana de entrega'),
        null=True
    )
    subscribed_to_newsletter = models.BooleanField(default=True, verbose_name='suscripto a newsletter')
    associated_user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        verbose_name=_(u'usuario vinculado'),
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _(u'cliente')
        verbose_name_plural = _(u'clientes')

    def __str__(self):
        return u"%s <%s> (%s)" % (self.name, self.email if self.email else u'sin email', self.address)

    def delivery_method_name(self):
        return self.prefered_delivery_method.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('delicontacts.views.account_settings')

deliorders/models.py
# -*- coding: utf-8 -*-

from decimal import Decimal

from django.db import models
from django.conf import settings
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.utils.encoding import python_2_unicode_compatible

from datetime import date

from django.utils.translation import ugettext_lazy as _
from delicontacts.models import Customer, CONTACT_MODE_CHOICES
from deliproducts.models import Price
from delidelivery.models import DeliveryMethod


ORDER_STATUS_CHOICES = (
    (10, _(u'Iniciada por el usuario')),
    (20, _(u'Confirmada por el usuario')),
    (100, _(u'Abierto')),
    (200, _(u'Cerrado')),
    (300, _(u'Entregado')),
    (400, _(u'Pagado pero no entregado')),
    (500, _(u'Entregado pero no pagado')),
    (600, _(u'Conciliado')),
)

DELIVERED_STATUSES = (300, 500)
USER_CONFIRMED_STATUSES = (20,)
CLOSED_STATUSES = (200, 300, 400, 500, 600)


class OrderManager(models.Manager):
    def get_active(self, customer):
        """Tries to get an unprocessed order for a customer."""
        try:
            o = Order.objects.get(customer=customer, status=10)
        except ObjectDoesNotExist:
            o = None
        return o

    def last_closed(self, number=10):
        return self.get_queryset().filter(status__gte=300).order_by('-when_closed')[:number]


@python_2_unicode_compatible
class Order(models.Model):
    code = models.CharField(
        max_length=50,
        unique=True,
        verbose_name=_(u'código'))
    customer = models.ForeignKey(
        Customer,
        verbose_name=_(u'cliente'),
        on_delete=models.SET_NULL,
        null=True)
    contact_mode = models.IntegerField(
        choices=CONTACT_MODE_CHOICES,
        blank=True,
        verbose_name=_(u'forma de contacto'))
    delivery_method = models.ForeignKey(
        DeliveryMethod,
        null=True,
        verbose_name=_(u'método de envío'))
    delivery_address = models.TextField(verbose_name=_(u'dirección de envío'), blank=True)
    delivery_date = models.DateField(
        verbose_name=_(u"fecha de entrega"),
        blank=True,
        null=True)
    delivery_price = models.DecimalField(
        max_digits=20,
        decimal_places=4,
        default=0.0,
        verbose_name=_(u'precio de envío'),
        help_text=_(u'Se completará automáticamente con la información del envío')
    )
    user_comments = models.TextField(verbose_name=_(u'notas del usuario'), blank=True)
    staff_comments = models.TextField(verbose_name=_(u'notas para el usuario'), blank=True)
    when_create = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_(u'fecha de pedido'))
    status = models.IntegerField(
        choices=ORDER_STATUS_CHOICES,
        default=100,
        verbose_name=_(u'estado'))
    reconciled = models.BooleanField(
        default=False,
        verbose_name=_(u'conciliado'))
    when_closed = models.DateField(
        null=True,
        verbose_name=_(u'fecha de cierre'))
    when_delivered = models.DateField(
        null=True,
        verbose_name=_(u'fecha de entrega'))

    objects = OrderManager()

    class Meta:
        verbose_name = _(u'pedido')
        verbose_name_plural = _(u'pedidos')

    def __str__(self):
        return u"%s: %s (%s)" % (
            self.code,
            self.customer,
            self.when_create.strftime('%d/%m/%Y'))

    def save(self, *args, **kwargs):
        if self.pk is None:
            last_id = Order.objects.aggregate(models.Max('id'))['id__max'] or 0
            current_id = last_id + 1
            year = date.today().strftime('%y')
            self.code = "P-" + str(year) + "-" + str(current_id).zfill(5)
        # Calculate closing dates automatically
        if self.when_closed is None and self.status > 100:
            self.when_closed = date.today()
        if self.when_delivered is None and self.status in DELIVERED_STATUSES:
            self.when_delivered = date.today()

        # Customer's prefered delivery method is default
        self.delivery_method = self.delivery_method or self.customer.prefered_delivery_method
        # Customer's default contact mode is default
        self.contact_mode = self.contact_mode or self.customer.contact_mode
        # Customer's default address is default
        self.delivery_address = self.delivery_address or self.customer.address

        # Include delivery price
        self.delivery_price = self.delivery_method.delivery_price

        # Calculate next delivery date
        if self.status in USER_CONFIRMED_STATUSES or self.is_closed():
            self.delivery_date = self.delivery_date or self.delivery_method.next_delivery_date()

        # If the order is closed, send notification email to user
        old_status = 0
        if self.pk:
            old_value = Order.objects.get(pk=self.pk)
            old_status = old_value.status
        # Send confirmation email only for orders generated in the web that are closed
        if self.contact_mode == 50 and old_status < 200 and self.status >= 200:
            self.send_close_email()

        return super(Order, self).save(*args, **kwargs)

    def is_closed(self):
        return self.status in CLOSED_STATUSES

    def get_order_total(self, include_delivery=True):
        total = self.orderitem_set.aggregate(
            total=models.Sum(
                models.ExpressionWrapper(
                    models.F('sell_price') * models.F('quantity'), output_field=models.DecimalField()
                )
            )
        )['total']
        total = total if total is not None else 0.0
        if include_delivery:
            total = float(total) + float(self.delivery_price)
        return Decimal(total)

    def get_order_total_without_delivery(self):
        return self.get_order_total(False)

    def send_close_email(self):
        absolute_url = settings.ABSOLUTE_URL
        message = "Need an HTML enabled email client"  # render_to_string("email/order_email.txt", {'order':self})
        html_message = render_to_string("email/order_email.html", {'url': absolute_url, 'order': self})
        send_mail(
            subject=u"Tu pedido está confirmado",
            from_email=u"Pedidos Organicos de mi Tierra <pedidos@organicosdemitierra.com>",
            message=message,
            html_message=html_message,
            recipient_list=[self.customer.email]
        )

    get_order_total.short_description = _(u"Total de pedido")


@python_2_unicode_compatible
class OrderItem(models.Model):
    order = models.ForeignKey(Order)
    quantity = models.IntegerField(verbose_name=_(u'cantidad'))
    product = models.ForeignKey(
        Price,
        verbose_name=_(u'producto'),
        on_delete=models.SET_NULL,
        null=True
    )
    sell_price = models.DecimalField(
        max_digits=20,
        decimal_places=4,
        blank=True,
        verbose_name=_(u'precio de venta (si difiere)')
    )
    comments = models.CharField(
        max_length=200,
        verbose_name='Notas',
        blank=True
    )

    class Meta:
        verbose_name = _(u'ítem de pedido')
        verbose_name_plural = _(u'ítems de pedido')

    def __str__(self):
        return u"%s: %d * $%.2f = $%.2f" % (
            self.product,
            self.quantity,
            self.item_sell_price(),
            self.item_total()
        )

    def save(self, *args, **kwargs):
        self.sell_price = self.sell_price or self.product.sell_price
        return super(OrderItem, self).save(*args, **kwargs)

    def item_sell_price(self):
        return self.sell_price if self.sell_price is not None else self.product.sell_price

    def item_total(self):
        return self.item_sell_price() * self.quantity

    def display(self):
        price = self.product
        product = price.product
        presentation = price.presentation
        presentation_disp = presentation.name if self.quantity == 1 else presentation.plural_name
        return _("{presentation} de {product} ({presentation_unit})").format(presentation=presentation_disp, product=product.name, presentation_unit=presentation.unit_display())

delicontacts/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import redirect
from django.forms.models import modelform_factory
from django.contrib.auth.decorators import login_required

from deliverest.decorators import render_to
from delicontacts.models import Customer
from deliorders.models import Order
from delidelivery.models import DeliveryMethod


@login_required
@render_to('account_settings.html')
def account_settings(request, *args, **kwargs):
    mode = kwargs.get('mode', 'settings')
    valid_modes = ['settings', 'orders']
    if mode not in valid_modes:
        raise ValueError("Mode '%s' does does not apply to this view" % (mode))
    user = request.user
    if not hasattr(user, 'customer'):
        try:
            # Associate the customer to the user if we can find it
            customer = Customer.objects.filter(email=user.email)[0]
            customer.associated_user = user
        except IndexError:
            # Fill out customer info from social data
            customer = Customer()
            customer.associated_user = user
            customer.name = user.first_name + ' ' + user.last_name
            customer.email = user.email
            customer.new = True
    else:
        customer = user.customer

    CustomerForm = modelform_factory(Customer, fields=('name', 'address', 'phone', 'prefered_delivery_method', 'subscribed_to_newsletter'))
    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        form.fields['prefered_delivery_method'].queryset = DeliveryMethod.objects.filter(is_active=True)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomerForm(instance=customer)
        form.fields['prefered_delivery_method'].queryset = DeliveryMethod.objects.filter(is_active=True)

    current_order = Order.objects.get_active(customer)
    can_add = current_order and current_order.status

    return {
        'form': form,
        'customer': customer,
        'mode': mode,
        'can_add': can_add
    }


@login_required
@render_to('delete_confirm.html')
def delete_account(request, *args, **kwargs):
    confirm = request.POST.get('confirm', False)
    if confirm == '1':
        from django.contrib.auth import logout
        request.user.delete()
        logout(request)
        return {
            'confirmed': True
        }
    return {
        'confirmed': False
    }

delicontacts/templates/account_settings.html
{% extends "organicos_base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container container-bar">
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="{% url 'account_settings_mode' mode='settings' %}" class="list-group-item">Información de la cuenta</a>
                {% if customer.order_set.last_closed.count %}
                <a href="{% url 'account_settings_mode' mode='orders' %}" class="list-group-item">Pedidos anteriores</a>
                {% endif %}
            </div>
            <div class="hidden-sm hidden-xs" id="cart-status">
            </div>
        </div>
        
        {% if mode == 'settings' %}
        <div class="col-md-9">
            <h2>{{ form.instance.name }}</h2>
            <h3>Actualizá la información de tu cuenta</h3>
            <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-info">
                        {% bootstrap_icon "star" %} Guardar
                    </button>
                    {% if not customer.new %}
                    <a class="btn btn-danger" href={% url 'account_delete' %}>
                        {% bootstrap_icon "remove" %} Eliminar mi cuenta
                    </a>
                    {% endif %}
                {% endbuttons %}
            </form>
        </div>
        {% elif mode == 'orders' %}
        <div class="col-md-9">
            <ul>
            {% for o in customer.order_set.last_closed %}
                <form action={% url 'load_order' %} method='post'>
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{ o.id }}" />
                <li><h3 class="history-order">{{o.code}} - {{o.when_closed}}&nbsp;<button type="button" class="btn btn-info" onclick="toggleOrder(this)">Mostrar</button>{% if can_add %}&nbsp;<button type="submit" class="btn btn-info">Agregar al pedido actual</button>{% endif %}</h3></li>
                <form>
                <ul>
                    {% for item in o.orderitem_set.all %}
                    <li class="history-order-item">{{ item.quantity }} {%if item.quantity == 1%}{{ item.product.presentation.name|lower }}{% else %}{{ item.product.presentation.plural_name|lower }}{% endif %} de <strong>{{ item.product.product.name|lower }}</strong></li>
                    {% endfor %}
                </ul>
            {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(function(){
    });
    function toggleOrder(obj) {
        $(obj).parent().parent().next().find('li').slideToggle();
        return false;
    }
</script>
{% endblock %}

delicontacts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
	{% for message in messages %}
	<li>{{message}}</li>
	{% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
	{% if user.is_authenticated %}
	<li><a href="{% url 'account_email' %}">Change E-mail</a></li>
	<li><a href="{% url 'account_logout' %}">Sign Out</a></li>
	{% else %}
	<li><a href="{% url 'account_login' %}">Sign In</a></li>
	<li><a href="{% url 'account_signup' %}">Sign Up</a></li>
	{% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

delicontacts/templates/delete_confirm.html
{% extends "organicos_base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container container-bar">
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="{% url 'account_settings_mode' mode='settings' %}" class="list-group-item">Información de la cuenta</a>
            </div>
            <div class="hidden-sm hidden-xs" id="cart-status">
            </div>
        </div>
        
        {% if confirmed == False %}
        <div class="col-md-9">
            <h1>Borrar cuenta</h1>
            <h2>¿Estás segura?</h2>
            <p>Gracias por haber confiado en nosotras este tiempo.</p>
            <p>En Orgánicos de mi Tierra respetamos tu privacidad. Al borrar tu cuenta, tus datos se borran
            definitivamente de nuestra base de datos. Todo tu historial y cualquier otra información
            que nos hayas confiado será eliminada y no es posible volver atrás.</p>
            <form method="POST" action="{% url 'account_delete' %}">
                {% csrf_token %}
                <input type="hidden" name="confirm" value="1" />
                <button type="submit" class="btn btn-danger">
                    {% bootstrap_icon "warning" %} Confirmar borrado de cuenta
                </button>
            </form>
        </div>
        {% endif %}
        {% if confirmed == True %}
        <div class="col-md-9">
            <h1>¡Hasta la próxima!</h1>
            <p>¡Esperamos poder volver a verte pronto!</p>
        </div>
        {% endif%}
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(function(){
    });
    function toggleOrder(obj) {
        $(obj).parent().parent().next().find('li').slideToggle();
        return false;
    }
</script>
{% endblock %}